services:
  - type: web
    name: taskflow-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://juljaht15-taskflow-project.vercel.app